project_name: stash-vr
builds:
  - main: ./cmd/stash-vr
    ldflags:
      - s -w -X stash-vr/internal/build.Version={{.Version}} -X stash-vr/internal/build.SHA={{.ShortCommit}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
universal_binaries:
  - replace: true

checksum:
  disable: true
changelog:
  skip: true
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  mode: keep-existing