version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    main: ./cmd/stash-vr
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -X {{ .ModulePath }}/internal/build.Version={{ .Version }} -X {{ .ModulePath }}/internal/build.SHA={{ .ShortCommit }} -s -w

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true
changelog:
  disable: true

dockers:
  - id: img-amd64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--cache-from=type=gha,scope=release-amd64"
      - "--cache-to=type=gha,mode=max,scope=release-amd64"
      - "--build-arg=BUILD_VERSION={{ .Version }}"
      - "--build-arg=BUILD_SHA={{ .ShortCommit }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - id: img-arm64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--cache-from=type=gha,scope=release-arm64"
      - "--cache-to=type=gha,mode=max,scope=release-arm64"
      - "--build-arg=BUILD_VERSION={{ .Version }}"
      - "--build-arg=BUILD_SHA={{ .ShortCommit }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
docker_manifests:
  - name_template: "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64"

release:
  mode: keep-existing
