version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    main: ./cmd/.ModulePath }}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -X {{ .ModulePath }}/internal/build.Version={{ .Version }} -X {{ .ModulePath }}/internal/build.SHA={{ .ShortCommit }} -s -w

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true
changelog:
  skip: true

# Build per-arch images and publish a multi-arch manifest
dockers:
  - id: img-amd64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: img-arm64
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName | lower }}:{{ .Tag }}-arm64"

release:
  mode: keep-existing
