project_name: stash-vr
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    main: ./cmd/stash-vr
    ldflags:
      - -X stash-vr/internal/build.Version={{.Version}} -X stash-vr/internal/build.SHA={{.Commit}} -s -w
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64]          # add arm64 if you need it

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  disable: true
changelog:
  skip: true

dockers:
  - use: buildx
    dockerfile: Dockerfile    # expects a Dockerfile at repo root
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:{{ .Tag }}"
      - "{{ .Env.DOCKER_USERNAME }}/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      -
release:
  mode: keep-existing
